name: Build Expo Android APK
on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Install Dependencies
        run: npm install --legacy-peer-deps

      - name: Prebuild Android Folder
        # We delete the old folder first to fix the 'unknown property' error
        run: |
          rm -rf android
          CI=1 npx expo prebuild --platform android --clean

      - name: Build APK with Gradle
        working-directory: ./android
        run: |
          chmod +x gradlew
          ./gradlew assembleRelease

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: mits-attendance-apk
          path: android/app/build/outputs/apk/release/*.apk
          retention-days: 1
